server:
  port: 9090

logging:
  level:
    "org.springframework": info
    "global.saveukraine": debug

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 50MB
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    jpa:
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          dialect: "org.hibernate.dialect.PostgreSQLDialect"
      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate:
        ddl-auto: update
  mail:
    host: smtp.gmail.com
    # sensitive data
    username: ${MAIL_USERNAME}
    # sensitive data
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true

mail:
  receiver: ${MAIL_RECEIVER}
  subject: "Заявка на волонтера"
  text-placeholder: "Имя: %s%nПол: %s%nГород: %s%nТелефон:%s"

cloud:
  aws:
    credentials:
      # sensitive data
      access-key: ${AMAZON_ACCESS_KEY}
      # sensitive data
      secret-key: ${AMAZON_SECRET_KEY}
    region:
      static: eu-central-1
    stack:
      auto: false
    bucket: ${AMAZON_BUCKET_NAME}